### ISSUE TITLE
Online indicator not usable on ipads/medium size screens

### ISSUE THREAD

**Issue by y2kmurali** [CarsonHoffman/office-hours-queue#26]
Really appreciate the online indicator for students, it saves quite a bit of time spent searching/pinging students that are no longer at OH. 

I use an ipad for OH and unfortunately it appears that the screen size is in the awkward middle ground between mobile and desktop - the indicator is not visible and can't be seen by scrolling horizontally/rotating the ipad. For now I've resorted to just using my phone to check if a student is offline, but that's not really ideal. 

The issue can be replicated on desktop as well by just making the window width of your web browser a little wider than half of the screen.

Some potential fixes would be to allow collapsing of the sidebar/stack for instructors (to give us more screen real estate) or potentially move the online/offline indicator to the top right corner of the box that we see rather than letting it be in the area that gets cut off horizontally.

**Comment by CarsonHoffman** [comment]
Thanks for the feedback. This specific issue is a symptom of a larger issue of me not really having any CSS experience to speak of and not fully utilizing the responsiveness characteristics of the underlying framework…I definitely should have been paying closer attention to this. I just pushed [a commit](https://github.com/CarsonHoffman/office-hours-queue/commit/76337420d9a05611aa90585a9fc962a7fc803020) that should hopefully address this and a few other issues that had been bugging me. This seems to be much better both in landscape and portrait on my 11" iPad. Let me know how this works out for you!

**Comment by y2kmurali** [comment]
Thanks Carson, looks a lot better! CSS is definitely black magic for me too.

There's still a slight bug I found if the text in the location field is too long and doesn't wrap - this is especially if a long link is posted in the location; because its a link and doesn't have any spaces to break/wrap around, the online/offline indicator still gets cut off.

**Comment by CarsonHoffman** [comment]
Could you share some more information about your environment? I successfully see the indicator in both landscape and portrait mode in both Safari and Chrome:
![image](https://user-images.githubusercontent.com/19721219/155757648-d4369b33-52b6-485b-b7b2-c038e042056e.png)
![image](https://user-images.githubusercontent.com/19721219/155757651-22164bcf-f308-4698-a2fa-fa8ec13970e8.png)

**Comment by y2kmurali** [comment]
Yeah sure, I'm on Safari on my ipad, here are some screenshots as to what it looks like on my end. Interestingly it seems to work fine on my laptop regardless of the window width. Note that for my use case (in person oh with my ipad) this isn't an issue, just figured I'd bring it up.

![CF433326-FA60-4695-94C5-48650D9C5CD5](https://user-images.githubusercontent.com/13545438/155763003-530631dd-0fcd-4af2-b359-d7de6abd870c.jpeg)
![4C4570C4-4B75-498B-BC51-24FD1C4BA0E3](https://user-images.githubusercontent.com/13545438/155763005-c96d4597-f77a-4506-b682-4a2c204ab5fe.jpeg)

**Comment by CarsonHoffman** [comment]
That's interesting. After some more investigation, it looks like `overflow-wrap: anywhere`—the property I use to force the link to break—isn't actually supported on Safari, but it still works on both macOS and iOS Safari for me; I cannot reproduce your case. Regardless, it seems like `word-break: break-all` might help here. I just added this, could you check to see if it helps on your end? (Safari really likes to hold onto caches, so you might need to manually clear them by connecting to a Mac and going through the Safari developer tools.)

**Comment by y2kmurali** [comment]
Yup, that seems to have fixed it! Wrapping still seems off on the "popped" modal but that's not a big deal as a hypothetical link would still be clickable and a normal entry would have places to break at.
